version: '3'
services:
#  database:
#    image: mysql:5.7
#    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: tp
#      MYSQL_USER: tp_admin
#      MYSQL_PASSWORD: tp_admin
#
#  rabbitmq:
#    build: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
  myapp:
    environment:
      - SPRING_PROFILES=local
#    entrypoint:
#      - /opt/docker-wait-for-others.sh
#      - rabbitmq:5672
#      - database:3306
#      - --
    command: /opt/docker-app-start.sh
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./docker-wait-for-it.sh:/opt/docker-wait-for-it.sh:ro
      - ./docker-wait-for-others.sh:/opt/docker-wait-for-others.sh:ro
#    depends_on:
#      - rabbitmq
#      - database
